#!/usr/bin/env perl
# -*- perl -*-

=head1 NAME

irc-sendq - Plugin to graph the sendq of a server's uplink(s) from Sentinel.

=head1 CONFIGURATION

You must set env.logfile to the sentinel.log file outputted by Sentinel.

  [irc-*]
    env.logfile  /home/sentinel/var/sentinel.log

=head1 AUTHOR

MrIron <iron@masterbofh.org>

=head1 LICENSE

GPLv3

=head1 MAGIC MARKERS

  #%# family=manual
  #%# capabilities=autoconf

=cut

use POSIX;
use Munin::Plugin;

my $LOGFILE = $ENV{'logfile'} || '/home/sentinel/var/sentinel.log';

my $modification = -M $LOGFILE;
my $lastupdated = ceil(time() - $modification);

my @uplinks;

if ($ARGV[0] and $ARGV[0] eq "autoconf") {
  if ( ! -r $LOGFILE ) {
    print "log file not found or wrong permissions\n";
    exit 0;
  }
  print "yes\n";
  exit 0;
}

open(LOG,$LOGFILE);
while(<LOG>)
{
	if ( /SENDQ_(.*)\:(\d+)$/ )
	{	
		$data{$1} = $2;
		push(@uplinks, $1);
	}
}

close(LOG);

if($ARGV[0] and $ARGV[0] eq "config") {
	print "host_name $ENV{FQDN}\n";
	print "graph_title irc sendq\n";
	print "graph_category irc\n";
	print "graph_vlabel SendQ in bytes\n";
	print "graph_order @uplinks\n";
	print "graph_args -l 0\n";

	foreach (@uplinks)
	{	
		print "$_.label $_\n";
		print "$_.draw LINE2\n";
	}

    exit 0;
}

foreach (@uplinks)
{
	print "$_.value $lastupdated:$data{$_}\n";
}
