#!/usr/bin/env perl
# -*- perl -*-

=head1 NAME

irc-lusers - Plugin to graph the number of local clients on an IRC network from Sentinel.

=head1 CONFIGURATION

You must set env.logfile to the sentinel.log file outputted by Sentinel.

  [irc-*]
    env.logfile  /home/sentinel/var/sentinel.log

=head1 AUTHOR

MrIron <iron@masterbofh.org>

=head1 LICENSE

GPLv3

=head1 MAGIC MARKERS

  #%# family=manual
  #%# capabilities=autoconf

=cut

use POSIX;
use Munin::Plugin;

my $LOGFILE = $ENV{'logfile'} || '/home/sentinel/var/sentinel.log';

my $modification = -M $LOGFILE;
my $lastupdated = ceil(time() - $modification);

if ($ARGV[0] and $ARGV[0] eq "autoconf") {
  if ( ! -r $LOGFILE ) {
    print "log file not found or wrong permissions\n";
    exit 0;
  }
  print "yes\n";
  exit 0;
}

if($ARGV[0] and $ARGV[0] eq "config") {
    print "host_name $ENV{FQDN}\n";
    print "graph_title irc local clients\n";
    print "graph_category irc\n";
    print "graph_order local_clients max_local_clients\n";
    print "graph_args -l 0\n";
    print "local_clients.label local clients\n";
    print "local_clients.draw LINE2\n";
    print "max_local_clients.label max local clients\n";
    print "max_local_clients.draw LINE2\n";
    exit 0;
}

open(LOG,$LOGFILE);
while(<LOG>)
{
	chop;
	my ($name,$value)=split(/:/);

	$data{$name} = $value;
}

close(LOG);

print "local_clients.value $lastupdated:$data{LOCAL_USERS}\n";
print "max_local_clients.value $lastupdated:$data{MAX_LOCAL_USERS}\n";
